name: quick_learn
description: learn anything quick

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_hooks: ^0.13.0
  dio: ^3.0.10
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  form_field_validator: ^1.0.1
  equatable: ^1.2.3
  hive: ^1.4.3
  hive_flutter: ^0.3.1
  flutter_bloc: ^6.0.1
  sized_context: ^0.2.1+1
  video_player: ^0.10.11+2
  carousel_slider: ^2.2.1
  firebase_storage: ^3.1.6
  path_provider: ^1.6.11
  firebase_core: ^0.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  hive_generator: ^0.7.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
#  assets:
#     - images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
